### ISSUE TITLE
TypeError: 'PretrainedCfg' object is not subscriptable

### ISSUE THREAD

**Issue by hunnieej** [CVIR/ConvPrompt#1] opened 2024-04-12 08:21 UTC
Hello, I have TypeError Issue for training with main cifar100-convprompt

pretrained_custom_load='npz' in pretrained_cfg['url'],
                                    ~~~~~~~~~~~~~~^^^^^^^
TypeError: 'PretrainedCfg' object is not subscriptable

could you check it?

**Comment by ranarag** [comment] 2024-04-12 08:35
Hi, this seems like an error with the pre-trained config for vit. Could you please share the entire log containing line numbers and file names?

**Comment by hunnieej** [comment] 2024-04-12 08:40
Here's the full log

File "/home/dbice/workspace/CL/ConvPrompt/main.py", line 206, in <module>
    main(args)
  File "/home/dbice/workspace/CL/ConvPrompt/main.py", line 53, in main
    model = create_model(
            ^^^^^^^^^^^^^
  File "/home/dbice/anaconda3/lib/python3.11/site-packages/timm/models/_factory.py", line 117, in create_model
    model = create_fn(
            ^^^^^^^^^^
  File "/home/dbice/workspace/CL/ConvPrompt/vision_transformer.py", line 1079, in vit_base_patch16_224_in21k
    model = _create_vision_transformer('vit_base_patch16_224_in21k', pretrained=pretrained, **model_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dbice/workspace/CL/ConvPrompt/vision_transformer.py", line 842, in _create_vision_transformer
    pretrained_custom_load='npz' in pretrained_cfg['url'],
                                    ~~~~~~~~~~~~~~^^^^^^^
TypeError: 'PretrainedCfg' object is not subscriptable

**Comment by ranarag** [comment] 2024-04-12 14:04
Sorry, I couldn't reproduce the error. Also, there is no ```PretrainedCfg``` in the code.
Did you by any chance make any changes to the code? 
Please see if ``` git checkout .``` helps.

**Comment by ranarag** [comment] 2024-04-16 05:45
I hope the issue has been solved. I am closing it.

**Closed as completed by ranarag** 2024-04-16 05:45 UTC
